### ISSUE TITLE
Hide name change message chat

### ISSUE THREAD

**Issue by Ketz1337** [oqyh/Game-Manager#1]
Is it possible to disable the name change message from the chat?

![csgo_namechange_chat](https://user-images.githubusercontent.com/23225942/156690706-732bb863-cf4f-4e7a-9290-88255f8b58ef.png)

**Comment by oqyh** [comment]
Added 1.0.3
-Hide Change Name Messages (Need To Enable sm_enable_hide_and_block) || 1= Yes || 0= No
sm_block_changename_message "0"
