### ISSUE TITLE
Unknown command

### ISSUE THREAD

**Issue by Truyn** [oqyh/Game-Manager#2]
[SM] Loaded plugin Game_Manager.smx successfully.
Unknown command "sm_block_all_radio_messages"

**Comment by oqyh** [comment]
Sorry for delay 
Fixed All block message + radio send to 
"sm_block_radio_voice_agents"


(1.0.4)
- Fix Bug
- Fix Unknown command "sm_block_all_radio_messages"
- Added Remove Auto Communication Penalties
- Added Block Footsteps Sounds
- Added Block Jump Land Sounds
