### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Truyn** [oqyh/Game-Manager#4]
L 06/20/2022 - 13:31:51: [SM] Exception reported: Invalid edict (-1 - -1)
L 06/20/2022 - 13:31:51: [SM] Blaming: Game_Manager.smx
L 06/20/2022 - 13:31:51: [SM] Call stack trace:
L 06/20/2022 - 13:31:51: [SM]   [0] GetEdictClassname
L 06/20/2022 - 13:31:51: [SM]   [1] Line 400, Game_Manager.sp::NSound_CallBack
L 06/20/2022 - 13:31:51: [SM]   [3] EmitSound
L 06/20/2022 - 13:31:51: [SM]   [4] Line 481, C:\sourcemod-1.10.0-git6528-windows\addons\sourcemod\scripting\include\sdktools_sound.inc::EmitSoundToAll
L 06/20/2022 - 13:31:51: [SM]   [5] Line 161, DropsSummoner.sp::Detour_RecordPlayerItemDrop

**Comment by oqyh** [comment]
updated Game_Manager (1.0.6)
