### ISSUE TITLE
Exception reported: Invalid edict (-1 - -1)

### ISSUE THREAD

**Issue by suspectykt** [oqyh/Game-Manager#5]
[CS:GO] Game Manager" (1.0.6) by Gold_KingZ
L 07/08/2022 - 01:02:46: [SM] Exception reported: Invalid edict (-1 - -1)
L 07/08/2022 - 01:02:46: [SM] Blaming: Game_Manager.smx
L 07/08/2022 - 01:02:46: [SM] Call stack trace:
L 07/08/2022 - 01:02:46: [SM]   [0] GetEdictClassname
L 07/08/2022 - 01:02:46: [SM]   [1] Line 1333, Game_Manager.sp::NSound_CallBack
L 07/08/2022 - 01:02:46: [SM]   [3] EmitSound
L 07/08/2022 - 01:02:46: [SM]   [4] Line 481, C:\sourcemod-1.10.0-git6528-windows\addons\sourcemod\scripting\include\sdktools_sound.inc::EmitSoundToAll
L 07/08/2022 - 01:02:46: [SM]   [5] Line 161, DropsSummoner.sp::Detour_RecordPlayerItemDrop

**Comment by oqyh** [comment]
Fixed Download 1.0.7

**Comment by oqyh** [comment]
Fixed Download [1.0.8](https://github.com/oqyh/Game-Manager/releases/tag/1.0.8)
