### ISSUE TITLE
Exception reported: Invalid edict (-1 - -1)

### ISSUE THREAD

**Issue by BOJEKAKAYAPOPKA** [oqyh/Game-Manager#6]
L 10/17/2022 - 12:56:10: [SM] Exception reported: Invalid edict (-1 - -1)
L 10/17/2022 - 12:56:10: [SM] Blaming: Game_Manager.smx
L 10/17/2022 - 12:56:10: [SM] Call stack trace:
L 10/17/2022 - 12:56:10: [SM]   [0] GetEdictClassname
L 10/17/2022 - 12:56:10: [SM]   [1] Line 1375, D:\Desktop\1.10\Game_Manager.sp::Call_Back_Sound
L 10/17/2022 - 12:56:10: [SM]   [3] EmitSound
L 10/17/2022 - 12:56:10: [SM]   [4] Line 433, <unknown>::EmitSoundToClient
L 10/17/2022 - 12:56:10: [SM]   [5] Line 291, <unknown>::Timer_SendRepeat

L 10/17/2022 - 12:01:44: [SM] Exception reported: Invalid edict (-1 - -1)
L 10/17/2022 - 12:01:44: [SM] Blaming: Game_Manager.smx
L 10/17/2022 - 12:01:44: [SM] Call stack trace:
L 10/17/2022 - 12:01:44: [SM]   [0] GetEdictClassname
L 10/17/2022 - 12:01:44: [SM]   [1] Line 1375, D:\Desktop\1.10\Game_Manager.sp::Call_Back_Sound
L 10/17/2022 - 12:01:44: [SM]   [3] EmitSound
L 10/17/2022 - 12:01:44: [SM]   [4] Line 483, D:\Download\JOB\ˮ𚀲ﱜinclude\sdktools_sound.inc::EmitSoundToAll
L 10/17/2022 - 12:01:44: [SM]   [5] Line 73, D:\Download\JOB\ˮ𚀲ﱜVIP_JoinSound.sp::VIP_OnVIPClientLoaded
L 10/17/2022 - 12:01:44: [SM]   [7] Call_Finish
L 10/17/2022 - 12:01:44: [SM]   [8] Line 66, vip/API.sp::CreateForward_OnVIPClientLoaded
L 10/17/2022 - 12:01:44: [SM]   [9] Line 201, vip/Clients.sp::Clients_OnVIPClientLoaded
L 10/17/2022 - 12:01:44: [SM]   [10] Line 303, vip/Clients.sp::Clients_LoadVIPFeatures
L 10/17/2022 - 12:01:44: [SM]   [11] Line 253, vip/Clients.sp::Clients_LoadVIPFeaturesPre
L 10/17/2022 - 12:01:44: [SM]   [12] Line 185, vip/Clients.sp::SQL_Callback_OnClientAuthorized

Version: Game Manager 1.0.7

**Comment by oqyh** [comment]
[Game Manager 1.0.7Fix.zip](https://github.com/oqyh/Game-Manager/files/9820664/Game.Manager.1.0.7Fix.zip)
here test this and tell me if you still got error make sure you restart server after drop smx

**Comment by BOJEKAKAYAPOPKA** [comment]
> [Game Manager 1.0.7Fix.zip](https://github.com/oqyh/Game-Manager/files/9820664/Game.Manager.1.0.7Fix.zip) here test this and tell me if you still got error make sure you restart server after drop smx

L 10/21/2022 - 10:26:43: [SM] Exception reported: Invalid edict (89 - 89)
L 10/21/2022 - 10:26:43: [SM] Blaming: Game_Manager.smx
L 10/21/2022 - 10:26:43: [SM] Call stack trace:
L 10/21/2022 - 10:26:43: [SM]   [0] GetEdictClassname
L 10/21/2022 - 10:26:43: [SM]   [1] Line 1376, D:\Desktop\ˮ�퀲ﱜ1.10\Game_Manager.sp::Call_Back_Sound
L 10/21/2022 - 11:50:25: [SM] Exception reported: Invalid edict (-1 - -1)
L 10/21/2022 - 11:50:25: [SM] Blaming: Game_Manager.smx
L 10/21/2022 - 11:50:25: [SM] Call stack trace:
L 10/21/2022 - 11:50:25: [SM]   [0] GetEdictClassname
L 10/21/2022 - 11:50:25: [SM]   [1] Line 1376, D:\Desktop\ˮ𚀲ﱜ1.10\Game_Manager.sp::Call_Back_Sound
L 10/21/2022 - 11:50:25: [SM]   [3] EmitSound
L 10/21/2022 - 11:50:25: [SM]   [4] Line 433, <unknown>::EmitSoundToClient
L 10/21/2022 - 11:50:25: [SM]   [5] Line 291, <unknown>::Timer_SendRepeat
L 10/21/2022 - 11:54:00: [SM] Exception reported: Invalid edict (88 - 88)
L 10/21/2022 - 11:54:00: [SM] Blaming: Game_Manager.smx
L 10/21/2022 - 11:54:00: [SM] Call stack trace:
L 10/21/2022 - 11:54:00: [SM]   [0] GetEdictClassname
L 10/21/2022 - 11:54:00: [SM]   [1] Line 1376, D:\Desktop\ˮ𚀲ﱜ1.10\Game_Manager.sp::Call_Back_Sound
L 10/21/2022 - 12:02:33: [SM] Exception reported: Invalid edict (-1 - -1)
L 10/21/2022 - 12:02:33: [SM] Blaming: Game_Manager.smx
L 10/21/2022 - 12:02:33: [SM] Call stack trace:
L 10/21/2022 - 12:02:33: [SM]   [0] GetEdictClassname
L 10/21/2022 - 12:02:33: [SM]   [1] Line 1376, D:\Desktop\ˮ𚀲ﱜ1.10\Game_Manager.sp::Call_Back_Sound
L 10/21/2022 - 12:02:33: [SM]   [3] EmitSound
L 10/21/2022 - 12:02:33: [SM]   [4] Line 433, <unknown>::EmitSoundToClient
L 10/21/2022 - 12:02:33: [SM]   [5] Line 291, <unknown>::Timer_SendRepeat
L 10/21/2022 - 12:26:31: [SM] Exception reported: Invalid edict (91 - 91)
L 10/21/2022 - 12:26:31: [SM] Blaming: Game_Manager.smx
L 10/21/2022 - 12:26:31: [SM] Call stack trace:
L 10/21/2022 - 12:26:31: [SM]   [0] GetEdictClassname
L 10/21/2022 - 12:26:31: [SM]   [1] Line 1376, D:\Desktop\ˮ𚀲ﱜ1.10\Game_Manager.sp::Call_Back_Sound
L 10/21/2022 - 12:27:30: [SM] Exception reported: Invalid edict (87 - 87)
L 10/21/2022 - 12:27:30: [SM] Blaming: Game_Manager.smx
L 10/21/2022 - 12:27:30: [SM] Call stack trace:
L 10/21/2022 - 12:27:30: [SM]   [0] GetEdictClassname
L 10/21/2022 - 12:27:30: [SM]   [1] Line 1376, D:\Desktop\ˮ𚀲ﱜ1.10\Game_Manager.sp::Call_Back_Sound

**Comment by oqyh** [comment]
[Game_Manager1.0.7Beta2.zip](https://github.com/oqyh/Game-Manager/files/9840734/Game_Manager1.0.7Beta2.zip)

This should work

**Comment by BOJEKAKAYAPOPKA** [comment]
> [Game_Manager1.0.7Beta2.zip](https://github.com/oqyh/Game-Manager/files/9840734/Game_Manager1.0.7Beta2.zip)
> 
> This should work

Moved from sm 1.10 to 1.11 but still have those exceptions

L 10/22/2022 - 14:23:39: [SM] Exception reported: Invalid edict (-1 - -1)
L 10/22/2022 - 14:23:39: [SM] Blaming: Game_Manager.smx
L 10/22/2022 - 14:23:39: [SM] Call stack trace:
L 10/22/2022 - 14:23:39: [SM]   [0] GetEdictClassname
L 10/22/2022 - 14:23:39: [SM]   [1] Line 1375, Game_Manager.sp::Call_Back_Sound
L 10/22/2022 - 14:23:39: [SM]   [3] EmitSound
L 10/22/2022 - 14:23:39: [SM]   [4] Line 433, D:\Desktop\Компилятор\1.10\include\sdktools_sound.inc::EmitSoundToClient
L 10/22/2022 - 14:23:39: [SM]   [5] Line 168, D:\Desktop\Компилятор\1.10\levelsranks_regbhop.sp::OnPlayerRunCmd

L 10/22/2022 - 14:56:07: [SM] Exception reported: Invalid edict (98 - 98)
L 10/22/2022 - 14:56:07: [SM] Blaming: Game_Manager.smx
L 10/22/2022 - 14:56:07: [SM] Call stack trace:
L 10/22/2022 - 14:56:07: [SM]   [0] GetEdictClassname
L 10/22/2022 - 14:56:07: [SM]   [1] Line 1375, Game_Manager.sp::Call_Back_Sound

L 10/22/2022 - 15:02:53: [SM] Exception reported: Invalid edict (102 - 102)
L 10/22/2022 - 15:02:53: [SM] Blaming: Game_Manager.smx
L 10/22/2022 - 15:02:53: [SM] Call stack trace:
L 10/22/2022 - 15:02:53: [SM]   [0] GetEdictClassname
L 10/22/2022 - 15:02:53: [SM]   [1] Line 1375, Game_Manager.sp::Call_Back_Sound

L 10/22/2022 - 16:11:01: [SM] Exception reported: Invalid edict (-1 - -1)
L 10/22/2022 - 16:11:01: [SM] Blaming: Game_Manager.smx
L 10/22/2022 - 16:11:01: [SM] Call stack trace:
L 10/22/2022 - 16:11:01: [SM]   [0] GetEdictClassname
L 10/22/2022 - 16:11:01: [SM]   [1] Line 1375, Game_Manager.sp::Call_Back_Sound
L 10/22/2022 - 16:11:01: [SM]   [3] EmitSound
L 10/22/2022 - 16:11:01: [SM]   [4] Line 483, D:\Download\JOB\Компилятор\include\sdktools_sound.inc::EmitSoundToAll
L 10/22/2022 - 16:11:01: [SM]   [5] Line 73, D:\Download\JOB\Компилятор\VIP_JoinSound.sp::VIP_OnVIPClientLoaded
L 10/22/2022 - 16:11:01: [SM]   [7] Call_Finish
L 10/22/2022 - 16:11:01: [SM]   [8] Line 66, vip/API.sp::CreateForward_OnVIPClientLoaded
L 10/22/2022 - 16:11:01: [SM]   [9] Line 201, vip/Clients.sp::Clients_OnVIPClientLoaded
L 10/22/2022 - 16:11:01: [SM]   [10] Line 303, vip/Clients.sp::Clients_LoadVIPFeatures
L 10/22/2022 - 16:11:01: [SM]   [11] Line 253, vip/Clients.sp::Clients_LoadVIPFeaturesPre
L 10/22/2022 - 16:11:01: [SM]   [12] Line 185, vip/Clients.sp::SQL_Callback_OnClientAuthorized

L 10/22/2022 - 16:13:21: [SM] Exception reported: Invalid edict (87 - 87)
L 10/22/2022 - 16:13:21: [SM] Blaming: Game_Manager.smx
L 10/22/2022 - 16:13:21: [SM] Call stack trace:
L 10/22/2022 - 16:13:21: [SM]   [0] GetEdictClassname
L 10/22/2022 - 16:13:21: [SM]   [1] Line 1375, Game_Manager.sp::Call_Back_Sound

**Comment by oqyh** [comment]
please add me on discord 
Gold KingZ#1337

**Comment by BOJEKAKAYAPOPKA** [comment]
> please add me on discord Gold KingZ#1337

* Gold KingZ#9909

**Comment by oqyh** [comment]
[Game_Manager1.0.7Beta5.zip](https://github.com/oqyh/Game-Manager/files/9855956/Game_Manager1.0.7Beta5.zip)

try this 
make sure remove old erro logs + restart server

**Comment by oqyh** [comment]
Fixed Download [1.0.8](https://github.com/oqyh/Game-Manager/releases/tag/1.0.8)
