### ISSUE TITLE
Sound Issues.

### ISSUE THREAD

**Issue by rcon420** [oqyh/Game-Manager#8]
Hi since I installed ur plugin I get complaints from players who say  - - Sometimes spot and hear random bullets hit the wall next to you. Even tho the person who was shot is on the opposite side of the map. It happens rarely, but it's weird. Sometimes it disturbs you on spotting enemies, and sometimes it actually feels like someone is cheating and you are the actual target.

Could this be somehow related to your plugin, let me know. Because it's very hard to reproduce this bug.

**Comment by oqyh** [comment]
that not my plugin for sure

-sm plugins list 
drop here cfg/sourcemod/Game_Manager.cfg

**Comment by oqyh** [comment]
hello rcon

i can confirm i got it today in official casual csgo its from the game + its rare yes.

it like bullets going near to your ear even the guy shooting cross the map not near to you

**Comment by rcon420** [comment]
> hello rcon
> 
> i can confirm i got it today in official casual csgo its from the game + its rare yes.
> 
> it like bullets going near to your ear even the guy shooting cross the map not near to you

I'm sorry for not getting back to you sooner! Thanks very informative, this should be flagged somehow to the valve then. my players complain about this once in 3-4 days. Before I thought this could be your plugin because your plugin interacts with sounds

**Comment by oqyh** [comment]
no problem
yes all sounds was checked not from plugin
