### ISSUE TITLE
Chicken friend message

### ISSUE THREAD

**Issue by BOJEKAKAYAPOPKA** [oqyh/Game-Manager#9]
Can you add hiding chicken friend message "Your chicken has been killed. She was yours for 1 seconds." in future updates

**Comment by oqyh** [comment]
+Added
// Hide Your Chicken Has Been Killed Messages (Need To Enable gm_enable_hide_and_block) || 1= Yes || 0= No
gm_block_chicken_message "0"

Game_Manager (1.1.0)
